steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dipg-server:$_BUILD_TAG'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dipg-server:latest'
      - '.'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/dipg-server:$_BUILD_TAG'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/dipg-server:latest'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dipg-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dipg-server:$_BUILD_TAG'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'DIPG_DATASET_PATH=surfiniaburger/dipg-eval-dataset'
      - '--cpu-boost'  # Enable CPU boost for faster startup
      - '--no-cpu-throttling'  # Don't throttle CPU during startup

images:
  - 'gcr.io/$PROJECT_ID/dipg-server:$_BUILD_TAG'
  - 'gcr.io/$PROJECT_ID/dipg-server:latest'

# Substitutions for manual builds
substitutions:
  _BUILD_TAG: 'manual'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
