import pytest
from med_safety_gym.crypto import generate_keys, sign_data, verify_signature

def test_sign_and_verify_cycle():
    """Verify that a signature generated by a private key is valid for the public key."""
    private_key, public_key = generate_keys()
    data = b"SafeClaw Manifest 2026"
    
    signature = sign_data(data, private_key)
    assert verify_signature(data, signature, public_key) is True

def test_tampered_data_fails():
    """Verify that changing the data invalidates the signature."""
    private_key, public_key = generate_keys()
    data = b"Original Data"
    tampered_data = b"Tampered Data"
    
    signature = sign_data(data, private_key)
    assert verify_signature(tampered_data, signature, public_key) is False

def test_wrong_key_fails():
    """Verify that a different public key cannot verify the signature."""
    private_key_1, public_key_1 = generate_keys()
    private_key_2, public_key_2 = generate_keys()
    data = b"Secret Message"
    
    signature = sign_data(data, private_key_1)
    assert verify_signature(data, signature, public_key_2) is False
